name: Install k3s
description: Install k3s with a specified Kubernetes version and verify the installation

inputs:
  kubernetes-version:
    description: 'The Kubernetes version to install with k3s'
    required: true
    default: 'v1.29.6'

runs:
  using: "composite"
  steps:
    - name: Install k3s
      shell: bash
      run: |
        export INSTALL_K3S_VERSION="${{ inputs.kubernetes-version }}+k3s1"
        curl -sfL https://get.k3s.io | sh -
        sudo chmod 777 /etc/rancher/k3s/k3s.yaml

    - name: Wait for k3s to start
      shell: bash
      run: sleep 15

    - name: Set kubectl context to k3s cluster
      shell: bash
      run: |
        echo "KUBECONFIG=/etc/rancher/k3s/k3s.yaml" >> $GITHUB_ENV

    - name: List available kubectl contexts
      shell: bash
      run: |
        kubectl config get-contexts

    - name: Verify k3s installation
      shell: bash
      run: |
        k3s --version
        kubectl version
        kubectl get node

    - name: Configure k3s registries
      shell: bash
      run: |
        echo '{
          "mirrors": {
            "registry.example.com:5000": {
              "endpoint": ["https://registry.example.com:5000"]
            }
          }
        }' | sudo tee /etc/rancher/k3s/registries.yaml
        sudo systemctl restart k3s

    # - name: Update Docker daemon to use k3s registry
    #   shell: bash
    #   run: |
    #     echo '{
    #       "insecure-registries" : ["https://registry.example.com:5000"]
    #     }' | sudo tee /etc/docker/daemon.json
    #     sudo systemctl restart docker

    # - name: Read registries
    #   shell: bash
    #   run: |
    #     cat /etc/docker/daemon.json
    #     cat /etc/rancher/k3s/registries.yaml

    - name: Install Tilt CLI
      shell: bash
      run: |
        curl -fsSL https://raw.githubusercontent.com/tilt-dev/tilt/master/scripts/install.sh | bash
        echo "export PATH=\$PATH:/usr/local/bin" >> $GITHUB_ENV
