name: Install k3s
description: Install k3s with a specified Kubernetes version and verify the installation

inputs:
  kubernetes-version:
    description: 'The Kubernetes version to install with k3s'
    required: true
    default: 'v1.29.6'

runs:
  using: "composite"
  steps:
    - name: Install k3s
      shell: bash
      run: |
        export INSTALL_K3S_VERSION="${{ inputs.kubernetes-version }}+k3s1"
        curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="server" sh -s - --flannel-backend none

    - name: Wait for k3s to start
      shell: bash
      run: sleep 15

    - name: Set kubectl context to k3s cluster
      shell: bash
      run: |
        echo "KUBECONFIG=/etc/rancher/k3s/k3s.yaml" >> $GITHUB_ENV

    - name: List available kubectl contexts
      shell: bash
      run: |
        echo $KUBECONFIG
        echo "Current kubectl context:"
        kubectl config get-contexts
        kubectl rename-context default k3s-default

    - name: Verify k3s installation
      shell: bash
      run: |
        k3s --version
        kubectl version
        kubectl get node

    - name: Install Tilt CLI
      shell: bash
      run: |
        curl -fsSL https://raw.githubusercontent.com/tilt-dev/tilt/master/scripts/install.sh | bash
        echo "export PATH=\$PATH:/usr/local/bin" >> $GITHUB_ENV

    - name: Verify Tilt installation
      shell: bash
      run: |
        tilt version
