name: Run k3s Server on Main Branch

on:
  push:
    branches:
      - main

jobs:
  start-k3s:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install and verify k3s
      uses: ./.github/actions/install-k3s
      with:
        kubernetes-version: 'v1.29.6'
