name: Run k3s Server on Main Branch

on:
  push:
    branches:
      - main

jobs:
  start-k3s:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install k3s
      run: |
        curl -sfL https://get.k3s.io | sh -
        sudo chmod 644 /etc/rancher/k3s/k3s.yaml

    - name: Wait for k3s to start
      run: sleep 15

    - name: Set kubectl context to k3s cluster
      run: |
        echo "KUBECONFIG=/etc/rancher/k3s/k3s.yaml" >> $GITHUB_ENV

    - name: List available kubectl contexts
      run: |
        kubectl config get-contexts

    - name: Verify k3s installation
      run: |
        k3s --version
        kubectl version
        kubectl get node
